apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo-create
  namespace: demo-ns
spec:

  # Mount path of the secrets backend
  mount: demo-db

  # Path to the secret
  path: creds/dev-postgres

  # Where to store the secrets, VSO will create the secret
  destination:
    create: true
    name: vso-db-demo-created

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-demo

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth