apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: app
  name: vault-kv-app
spec:
  type: kv-v2
  # mount path
  mount: kvv2
  
  # name of the secret
  name: webapp/config

  # dest k8s secret
  destination:
    name: secretkv
    create: true

  # static secret refresh interval
  refreshAfter: 30s